### ISSUE TITLE
Subroutine definition clobbered

### ISSUE THREAD

**Issue by fredhs** [bkubicek/grecode#3]
Thanks for sharing your code here, Bernhard. Today, I ran "grecode" for the first time and encountered an issue. I was trying to mirror and shift "FLY.ngc" with the following command:
    grecode -o mirr_shift.ngc  "/media/transfer/FLY/ver 02/FLY.ngc" -xflip -shift 25 0

All subroutine definitions in "FLY.ngc", e.g.

```
    o<3000> sub
    G0 X13.884 Y1.881
    ...
  o<3000> endsub
```

came out clobbered like this:

```
   O 3000> sub
    G0 X11.11600  Y1.881 
    ....
  O 3000> endsub
```

I'd appreciate your help.

[Sorry, I had to add fenced blocks to get the code displayed correctly].

Kind regards,
Fred

**Comment by bkubicek** [comment]
i have honestly not tried with subroutines, as I never used them apart from
my implementation in the marlin 3d printer firmware.
I will see when I find time to do that.
However, its quite possible that this will not fix, because the gcode
parser I wrote to then interpret all the flipping does not understand
subroutines.

Bernhard

**Comment by fredhs** [comment]
OK, thank you, Bernhard.

Fred
